@pid = b9588743-34cf-4451-afff-7897ce76869c


###

POST http://localhost:8000/projects HTTP/1.1
Content-Type: application/json

{
    "project_name": "frog-routes"
}

###

POST http://localhost:8000/projects HTTP/1.1
Content-Type: application/json

{
    "project_name": "my-movie-app"
}

###

GET http://localhost:8000/projects/{{pid}}



###

DELETE http://localhost:8000/projects/{{pid}}