@pid = 799c9404-6a89-494f-b411-b60706b7e424


###

POST http://localhost:8000/projects HTTP/1.1
Content-Type: application/json

{
    "project_name": "frog-routes-test"
}

###

POST https://frog-routes.fly.dev/projects HTTP/1.1
Content-Type: application/json

{
    "project_name": "frog-routes-test"
}

###

POST http://localhost:8000/projects HTTP/1.1
Content-Type: application/json

{
    "project_name": ""
}

###

POST http://localhost:8000/projects HTTP/1.1
Content-Type: application/json

{
    "project_name": "my-movie-app"
}

###

GET http://localhost:8000/projects/{{pid}}



###

DELETE http://localhost:8000/projects/{{pid}}


###

DELETE https://frog-routes.fly.dev/projects/{{pid}}