@pid = b9588743-34cf-4451-afff-7897ce76869c


###
POST http://localhost:8000/projects/{{pid}}/routes?path=/users&verb=delete HTTP/1.1
Content-Type: application/json

{
    "firstName": "Pei",
    "lastName": "Wu"
}

###

POST http://localhost:8000/projects/{{pid}}/routes?path=/teams&verb=get HTTP/1.1
Content-Type: application/json

{
    "firstName": "Pei",
    "lastName": "Wu"
}


###

GET http://localhost:8000/projects/{{pid}}/routes HTTP/1.1
