POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "public_id": "lethalspoons",
  "password": "youCant%know#It"
}

###

POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "public_id": "pswu11",
  "password": "youCant%know#It"
}

###

POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "public_id": "guest",
  "password": "youCant%know#It",
  "email": "guest@pm.me"
}

### 

GET http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "public_id": "pswu11"
}

### 

GET http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "email": "guest@pm.me"
}

###

DELETE http://localhost:8000/users/pswu11 HTTP/1.1