# fly.toml app configuration file generated for frog-routes on 2023-08-13T21:20:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frog-routes"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
